#may have to change according to CHATGPT because "npm run start" is not ok for production builds, only use for fast development
FROM node:14 AS react-build
WORKDIR /app
COPY ./streamlit_app/frontend /app/
RUN npm install
CMD ["npm", "run", "start"]